services:
  mysql:
    image: mysql:8.0
    container_name: enrollment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: enrollment_system
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  enrollment-system-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: